### ISSUE TITLE
design questions:

### ISSUE THREAD

**Issue by bodobalazs** [bobvdvelde/robout#2]
should the output of the function be a generator? should that yield tables of 1 or N rows?

**Comment by MatsWillemsen** [comment]
I'm currently writing it so that it returns one DataFrame with all the rows in it. Could rewrite it so that it yields series as well.

**Comment by bodobalazs** [comment]
same here, but i was wondering if the df has 16k rows, would it be a problem?

**Comment by MatsWillemsen** [comment]
No, pandas is more than ready for 16k rows. I've processed DataFrames with over 5 million records without any issues.

**Comment by bramiozo** [comment]
Of course It completely depends on the available internal memory. 

The use of a generator is not a bad idea if the resources are limited but that implies a type change based on the size of the request, or we can make the output type user-settable, out of scope for now but we can change this later.

**Comment by bobvdvelde** [comment]
The current setup is not oriented towards big-data analysis. As the target use-case is individual analysis in python notebooks with limited rights on a single shared resource, we should not expect datasets to become problematically big. In addition, the use of single tabular output formats is far closer to the datasets common in social sciences. As such, they supposedly raise a significantly smaller barrier to entry for non-programming colleagues that normally work with SPSS-like environments. 

We can discuss other uses after the tutorial.
